### ISSUE TITLE
Overly Aggressive Error Reporting

### ISSUE THREAD

**Issue by DevHog** [altoscode/vscode-quiksass#13]
The error reporter is quite aggressive in that it is reporting errors as I type, flicking up onscreen in the right bottom corner. 
If you begin to type a class - it fires an error as you haven't added brackets. If you begin to type a property of a class, you now have an error as it is expecting a : and then a ;  so now you have three errors stacked in the corner of the screen distracting you. 
Then you finish and hit save for it to compile, and you have no idea if there are errors or not because if you've typed up a set of properties for a class for just a few lines there can be over 10 errors. So you have to manually clear the error stack and save again to see if there is an error. 

The Error reporter needs a delay on typing - if you are typing it needs to not report an error - or at least only report an error on attempted save/compile.

**Comment by akkumar** [comment]
The compile gets triggered on `vscode.workspace.onDidSaveTextDocument` so it is possible that autosave was enabled in the IDE global settings to trigger the same. 

I have made a release (check 0.0.30) that contains a bunch of changes / configuration in case the defaults are not enough:

* `quiksass.pauseInterval` configuration property added ( value: number in seconds ). This prevents the compiler from getting triggered frequently.  Default: 10 seconds. 
* `quiksass.disableCompileOnSave`: default: false.  This is just in case - we do not want to compile with every save. 

New command added: 
"QuikSass: Compile Current File" (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>L</kbd>) - To trigger compilation manually of the current file. 

Hopefully this helps maintain the right balance between auto compilation and not being too eager to hog the cpu. 

Let me know if this helps.

**Comment by DevHog** [comment]
That works perfectly.

**Comment by akkumar** [comment]
If you are happy with the extension - you can star the extension here at -

https://marketplace.visualstudio.com/items?itemName=altoscode.quiksass :)

It helps to spread the word :)
